### ISSUE TITLE
Have you researched the eye tracking solution of Apple Vision Pro?

### ISSUE THREAD

**Issue by suliri** [EyeTrackVR/EyeTrackVR#108]
![NHLPItq0Oqbz729456pB (1)](https://github.com/EyeTrackVR/EyeTrackVR/assets/13286397/667b92e1-3a33-4b48-b308-d8f096fb0aae)

**Comment by RedHawk989** [comment]
Hello, this is to be used for issues with the software. This is irrelevant and will be closed. If you would like to discuss topics such as this, please reach out to the discord https://discord.gg/e9QfQQC6Cn

**Comment by RidgeXR** [comment]
lmao
