### ISSUE TITLE
Foveated rendering support

### ISSUE THREAD

**Issue by RedHawk989** [EyeTrackVR/EyeTrackVR#11]
Add some form of foveated rendering support either through mod, or directly. Requires lower latency of camera  feed transmission.

**Comment by Fxsch** [comment]
I hope this is the right place to ask but is it possible to use this for foveated rendering?

**Comment by RedHawk989** [comment]
We already have alpha tests with it, just waiting on some calibration fixes from me that I'll get to when updated documentation is finished. https://twitter.com/Prohurtz_/status/1737300797661028807?t=EkE6RYeVsqXc7QMRCX7jOQ&s=19
