### ISSUE TITLE
Improve Tracking/Lack thereof with threshold

### ISSUE THREAD

**Issue by C9Glax** [EyeTrackVR/EyeTrackVR#116]
https://github.com/user-attachments/assets/fb60e2c5-768a-4c67-8291-5308c978b5d0

(i know that leap isn't the algorithm you want to use here...)

Don't know how well this would play with the current tracking algorithms, and whether some of these already do this.
But it would also probably make sense if there is no eye/pupil detected, that the other simulates a rough value.

**Comment by RedHawk989** [comment]
RANSAC is an automatic adjusting threshold, AHSRAC and HSRAC use RANSAC for second-stage fine-tuning, and BLOB also uses a threshold.

> make sense if there is no eye/pupil detected, that the other simulates a rough value.
that is what outer eye falloff is for.

**Comment by C9Glax** [comment]
The Outer Eye Falloff I see now, thought that it would only use dominant eye in that case...

Is there a possibility to manually adjust the thresholds? Every setup is slightly different, and while I am sure that these are already doing a pretty good job, I could see a human filtering out pupils/corneas even better?

**Comment by RedHawk989** [comment]
All of these features are supported in the app already. I suggest you mess around with them. in the v2 app, most settings have tooltips.
