### ISSUE TITLE
Safety docs are missing

### ISSUE THREAD

**Issue by Luois45** [EyeTrackVR/EyeTrackVR#88]
### PROBLEM DESCRIPTION
_The 3 documentation documents about the safety of the IR Emitters are missing and the links are leading to a 404 page._

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [X] Read the [Contributing Guide and Policy](https://github.com/RedHawk989/EyeTrackVR/repo-tools/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/RedHawk989/EyeTrackVR/CODE_OF_CONDUCT.md)
- [X] Searched the problem in [issues](https://github.com/RedHawk989/EyeTrackVR/issues)
- [X] Searched the problem in [discussions](https://github.com/RedHawk989/EyeTrackVR/discussions)
- [X] Searched the problem in the [docs](https://redhawk989.github.io/EyeTrackVR/FAQ)
- [X] Searched the problem in the [chat](https://redhawk989.github.io/EyeTrackVR/contact/)

### SCREENSHOTS
![image](https://github.com/EyeTrackVR/EyeTrackVR/assets/58306774/7c884c59-24c9-4b23-8496-faa28311bd22)

**Comment by RedHawk989** [comment]
fixed, it was an issue from when we moved everything to this org.
