### ISSUE TITLE
On installation not working on Windows

### ISSUE THREAD

**Issue by Abhinav0002** [EyeTrackVR/EyeTrackVR#95]
Downloaded the .exe file from github, but only a blank cmd window is displayed on running the application and 

No settings file found, using base settings displayed in cmd

**Comment by RedHawk989** [comment]
I need more information. What .exe, did it ever work and what app version?

**Comment by Abhinav0002** [comment]
The eyetrack setup.exe file, and version is 0.1.8.1

**Comment by RedHawk989** [comment]
Can you launch the app through a command prompt? (open a command prompt in the same folder as the exe and then type the exe name. Ex: eyetrackapp.exe

You should get an output. Paste it here.

**Comment by Abhinav0002** [comment]
> Can you launch the app through a command prompt? (open a command prompt in the same folder as the exe and then type the exe name. Ex: eyetrackapp.exe
> 
> You should get an output. Paste it here.

I tried to launch it through the cmd and I am getting the same thing:

No settings file found, using base settings and after that nothing loads

**Comment by Abhinav0002** [comment]
Nothing else is displayed on the cmd 
![Screenshot 2023-10-13 134011](https://github.com/EyeTrackVR/EyeTrackVR/assets/54789584/6327ce40-2306-4aa1-8094-8e06a05a6f62)

**Comment by RedHawk989** [comment]
Have you tried just running from source? This is a very unusual error.

**Comment by RedHawk989** [comment]
Issue is stale. Closing.
