### ISSUE TITLE
Eyetracking wont start without having Hsrac and crashes with any other algo

### ISSUE THREAD

**Issue by julianpoelmann** [EyeTrackVR/EyeTrackVR#96]
soooo i just tried this tool as the pimax crystal doesnt provide openness value's buuut it seems ive ran into an issue. hsrac does work but is extremely unstable even after calibrating so i tried others. leap seems to work but just crashes leaving behind this message

![afbeelding](https://github.com/EyeTrackVR/EyeTrackVR/assets/28513665/18c1aa75-f234-405c-aedc-0ba63d148cf9)

it will only work if i select hsrac again altough leap is providing way better results. is there any way i can fix this?

im running on 0.2.0 BETA 8

**Comment by RedHawk989** [comment]
Beta 8?? That has not been released. If you are using the latest beta on Git Hub and not the one on Discord then that makes sense. Not all beta builds are tested, since they are automatically built when in development. Please do not use them.

**Comment by RedHawk989** [comment]
This is the latest semi tested build:  https://github.com/EyeTrackVR/EyeTrackVR/releases/tag/v1.0.0-HSF-and-new-algos-feature-branch.8

**Comment by julianpoelmann** [comment]
does this beta do the pimax crystal stuff? the tutorial stated i had to use the latest version in order to connect it or something with brokeneye

**Comment by RedHawk989** [comment]
I don't even know what you are talking about. We don't interface with pimax anything, and nothing brokeneye

**Comment by RedHawk989** [comment]
Interesting, okay, thanks! Well if that version works for you, I'm going to close this issue.

**Comment by julianpoelmann** [comment]
aaand the starting issue is still there and the crashing has returned

**Comment by sveken** [comment]
> aaand the starting issue is still there and the crashing has returned

I have seen that error if you take the headset off, Try start and run etvr while wearing it.

**Comment by RedHawk989** [comment]
@julianpoelmann disable ellipse-based openness then.
